// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZx2t_ayVvnZ_SP1EhL0tEHDiFSPPfgG8',
    appId: '1:352484013726:web:764413a05c7e42af072d8f',
    messagingSenderId: '352484013726',
    projectId: 'todo-coder',
    authDomain: 'todo-coder.firebaseapp.com',
    storageBucket: 'todo-coder.appspot.com',
    measurementId: 'G-PJK7QE9EGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW7v-lo9mRweFSHpY8La_UQwXjBF9G0S0',
    appId: '1:352484013726:android:202d338cb93c6703072d8f',
    messagingSenderId: '352484013726',
    projectId: 'todo-coder',
    storageBucket: 'todo-coder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCosHHvIJGTKPGxxzTqjkbeXyhZYJQd-5g',
    appId: '1:352484013726:ios:a6e7acd5787e78b5072d8f',
    messagingSenderId: '352484013726',
    projectId: 'todo-coder',
    storageBucket: 'todo-coder.appspot.com',
    iosBundleId: 'com.example.todoCoder',
  );
}
